# Generated by Django 6.0 on 2025-12-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('idmedico', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('especilizacao', models.CharField(max_length=100)),
                ('crm', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
